version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3 
  aws-eks: circleci/aws-eks@0.2.3

jobs:
  build-app:
    docker:
      # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/app

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - ./venv

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
  build-image:
    machine: true
    steps:
      - checkout
      - run:
          name: Create repository
          command:
            aws ecr describe-repositories --region us-east-1 --repository-names capstoneproj || aws ecr create-repository --region us-east-1 --repository-name capstoneproj
            # aws ecr create-repository --region us-east-1 --repository-name capstoneproj || true
      - run:
          name: Build image and push to docker
          command: |
              docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASS}
              docker build -t capstoneproj:latest .
              docker images ls
              docker tag capstoneproj ${DOCKER_USERNAME}/capstoneproj:latest
              docker push ${DOCKER_USERNAME}/capstoneproj:latest
  deploy-app:
    machine: true
    steps:
      - checkout
      - run:
          name: Install AWS CLI dependencies
          working_directory: /tmp
          command: |
            sudo apt-get update && sudo apt-get install -yy less
            sudo apt-get install unzip -y
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
      - run:
          name: Deploy Docker Container Image to Amazon ECR
          command: |
            echo "Pre-Build Steps:"
            echo "authenticating with AWS ECR..."
            
            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 162041392922.dkr.ecr.us-east-1.amazonaws.com
            
            echo "Build Steps:"
            echo "building image..."
            
            docker build -t 162041392922.dkr.ecr.us-east-1.amazonaws.com/capstoneproj:latest .
            
            echo "Post-Build Steps:"
            echo "pushing image to AWS ECR..."
            
            docker push 162041392922.dkr.ecr.us-east-1.amazonaws.com/capstoneproj:latest
            
            echo "updating AWS ECS service..."
            aws ecs update-service --cluster capstoneproj-cluster --service caostoneproj-sv --force-new-deployment --no-cli-pager
            
            echo "Done!"
        
workflows:
  default:
    jobs:
      - build-app
      - build-image:
          requires: [build-app]
          filters:
            branches:
              only: [main]
      - deploy-app:
          requires: [build-image]