apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneproj
  labels:
    app: capstoneproj
spec:
  selector:
    matchLabels:
      app: capstoneproj
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstoneproj
    spec:
      containers:
      - name: capstoneproj
        image: iroleh/capstoneproj:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstoneproj
  labels:
    app: capstoneproj
spec:
  # automatically create an external load-balanced IP for the service.
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: capstoneproj