apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneproj
  labels:
    app: capstoneproj
spec:
  selector:
    matchLabels:
      app: capstoneproj
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstoneproj
    spec:
      containers:
      - name: capstoneproj
        image: iroleh/capstoneproj:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080